### ISSUE TITLE
Sometimes Time is negative(<0)

### ISSUE THREAD

**Issue by q792602257** [boykathemad/xdebug-trace-viewer#3]
![image](https://user-images.githubusercontent.com/22654253/56857633-c3140b80-69a2-11e9-84c8-607004201a8a.png)
In var _stack ; TimeStart > 0 and TimeEnd is 0
![图片](https://user-images.githubusercontent.com/22654253/56857695-6d8c2e80-69a3-11e9-851c-cd1d7009e25c.png)

**Comment by q792602257** [comment]
I have no idea about how to fix this TAT

**Comment by gasparportik** [comment]
Hi @q792602257, please try this again with the latest commit I made, in my case that resolved the issues.
Also if you can please let me know what Xdebug version you're using, and read the notes section of the readme.

**Comment by q792602257** [comment]
it still have the problem with xdebug 2.7.2 and the latest commit
![图片](https://user-images.githubusercontent.com/22654253/57288357-e69a2d00-70eb-11e9-8349-dacd35f9da9e.png)
[Here](https://drive.google.com/open?id=11_dvgI9TXpe_Xhz4s1eNcvLDYufE0_5x) is the file generated by xdebug 2.7.2

**Comment by gasparportik** [comment]
Thanks for the sample, I checked and the issue still exists, I'll have to investigate further.

**Comment by q792602257** [comment]
OK ^_^

**Comment by gasparportik** [comment]
BTW, if you have any sensitive information in that trace, make sure to remove it from your drive and remove the link from the comment.

**Comment by q792602257** [comment]
I will, thanks noticing me

**Comment by gasparportik** [comment]
This should be resolved in the new version. It only affected the parallel parser, but that was the default in the WPF gui version.
@q792602257 I tested this with your sample trace and worked fine, let me know if found traces that still don't work properly.
